name: Build & Test (WIP)

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
    - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps: 
    - name: Setup env
      run: |
        apt install meson
      
