name: Build & Check

on: 
  pull_request:
    branches:
    - main

jobs:
  native-build:
    name: "Native Build"
    runs-on: ubuntu-latest
    steps: 
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install gettext valac meson libadwaita-1-dev libarchive-dev libgee-0.8-dev libgtk-4-dev libjson-glib-dev libsoup-3.0-dev desktop-file-utils appstream-util
    - name: Checkout pull request
      uses: actions/checkout@v4.2.2
      with:
          ref: ${{ github.event.pull_request.head.sha }}
    - name: Build
      run: |
        mkdir build
        meson --prefix=/usr build
        meson compile -C build
    - name: Check
      run: 'meson test -C build --print-errorlogs || :'

  flatpak-build:
    name: "Flatpak Build"
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-48
      options: --privileged
    steps:
    - name: Checkout pull request
      uses: actions/checkout@v4
    - name: Build
      uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: protonplus.flatpak
        manifest-path: com.vysp3r.ProtonPlus.local.yml
        cache-key: flatpak-builder-${{ github.sha }}
